### ISSUE TITLE
Missing private key configuration

### ISSUE THREAD

**Issue by jmriego** [transferwise/pipelinewise-tap-snowflake#68]
**Is your feature request related to a problem? Please describe.**
This tap does not work with a private key but requires user and password. In an enterprise production environment it's better practice to use private keys instead.

**Describe the solution you'd like**
Allow configuration of the connector with private keys

**Describe alternatives you've considered**
None that apply

**Additional context**
I have already submitted the #49 pull request 5 months ago so I'm opening this issue just in case it gives it more visibility

**Comment by Samira-El** [comment]
Feature added by https://github.com/transferwise/pipelinewise-tap-snowflake/pull/49.

Closing this.
